// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/llmons/who-is-the-undercover/internal/base/conf"
	"github.com/llmons/who-is-the-undercover/internal/base/data"
	"github.com/llmons/who-is-the-undercover/internal/base/server"
	"github.com/llmons/who-is-the-undercover/internal/controller"
	"github.com/llmons/who-is-the-undercover/internal/repo"
	"github.com/llmons/who-is-the-undercover/internal/router"
	"github.com/llmons/who-is-the-undercover/internal/service"
)

// Injectors from wire.go:

func initApplication(debug bool, serverConf *conf.Server, dbConfig *data.Database) (*gin.Engine, func(), error) {
	engine, err := data.NewDB(debug, dbConfig)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(engine)
	if err != nil {
		return nil, nil, err
	}
	undercoverRepo := repo.NewUndercoverRepo(dataData)
	undercoverService := service.NewUndercoverService(undercoverRepo)
	undercoverController := controller.NewUndercoverController(undercoverService)
	apiRouter := router.NewAPIRouter(undercoverController)
	ginEngine := server.NewHTTPServer(debug, apiRouter)
	return ginEngine, func() {
		cleanup()
	}, nil
}
