CREATE DATABASE IF NOT EXISTS undercover_game;

USE undercover_game;

CREATE TABLE word_pair (
    id BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    civ_word VARCHAR(255) NOT NULL DEFAULT '',
    uc_word VARCHAR(255) NOT NULL DEFAULT '',
    score FLOAT NOT NULL DEFAULT 0,
    source VARCHAR(255) NOT NULL DEFAULT 'manual'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO word_pair (civ_word, uc_word, score, source) VALUES
('苹果', '香蕉', 7.5, 'manual'),
('狗', '猫', 8.0, 'manual'),
('汽车', '自行车', 6.8, 'manual'),
('太阳', '月亮', 9.2, 'manual'),
('水', '火', 7.1, 'manual'),
('国王', '皇后', 8.3, 'manual'),
('大海', '湖泊', 6.5, 'manual'),
('电脑', '笔记本', 8.7, 'manual'),
('桌子', '椅子', 7.0, 'manual'),
('手机', '平板', 7.2, 'manual'),
('面包', '蛋糕', 6.4, 'manual'),
('云', '雾', 5.9, 'manual'),
('山', '丘陵', 8.1, 'manual'),
('河流', '溪流', 7.5, 'manual'),
('城市', '乡镇', 6.6, 'manual'),
('窗户', '门', 7.4, 'manual'),
('帽子', '头巾', 5.8, 'manual'),
('书', '杂志', 8.2, 'manual'),
('火车', '地铁', 7.3, 'manual'),
('相机', '录像机', 8.6, 'manual'),
('音乐', '歌曲', 9.0, 'manual'),
('冰', '雪', 7.1, 'manual'),
('花朵', '树木', 6.7, 'manual'),
('灯光', '台灯', 5.6, 'manual'),
('钢笔', '铅笔', 8.0, 'manual'),
('鱼', '虾', 7.5, 'manual'),
('衬衫', '夹克', 7.2, 'manual'),
('牛奶', '奶酪', 6.3, 'manual'),
('飞机', '直升机', 8.4, 'manual'),
('道路', '街道', 6.7, 'manual'),
('手表', '时钟', 8.1, 'manual'),
('床', '沙发', 6.5, 'manual'),
('游戏', '运动', 7.3, 'manual'),
('水果', '蔬菜', 7.0, 'manual'),
('椅子', '凳子', 5.7, 'manual'),
('信件', '邮件', 6.9, 'manual'),
('汤', '面条', 7.2, 'manual'),
('叶子', '树枝', 6.4, 'manual'),
('猴子', '猩猩', 7.5, 'manual'),
('蛋糕', '饼干', 6.6, 'manual'),
('钥匙', '锁', 8.3, 'manual'),
('火', '烟', 5.5, 'manual'),
('歌手', '舞者', 7.1, 'manual'),
('苹果', '梨', 6.8, 'manual'),
('篮球', '足球', 7.4, 'manual'),
('袜子', '鞋子', 7.2, 'manual'),
('鲸鱼', '海豚', 8.6, 'manual'),
('枕头', '毯子', 6.3, 'manual'),
('学校', '大学', 8.5, 'manual'),
('笔记本', '日记本', 7.3, 'manual'),
('叉子', '勺子', 6.4, 'manual'),
('地球', '火星', 8.7, 'manual'),
('黄色', '橙色', 7.5, 'manual'),
('医生', '护士', 8.2, 'manual'),
('老师', '学生', 7.2, 'manual'),
('厨师', '面包师', 6.8, 'manual'),
('工程师', '建筑师', 7.5, 'manual'),
('法官', '律师', 8.4, 'manual'),
('蝴蝶', '蜜蜂', 7.3, 'manual'),
('青蛙', '蜥蜴', 6.7, 'manual'),
('狮子', '老虎', 8.7, 'manual'),
('熊猫', '考拉', 7.5, 'manual'),
('龙', '凤凰', 9.0, 'manual'),
('星星', '行星', 8.6, 'manual'),
('音乐', '绘画', 7.2, 'manual'),
('蜂蜜', '糖', 6.4, 'manual'),
('土豆', '胡萝卜', 5.8, 'manual'),
('白菜', '生菜', 6.5, 'manual'),
('蜡烛', '火把', 7.0, 'manual'),
('戒指', '项链', 8.4, 'manual'),
('马', '驴', 6.7, 'manual'),
('鹦鹉', '乌鸦', 7.2, 'manual'),
('船', '小艇', 7.0, 'manual'),
('手套', '连指手套', 6.5, 'manual'),
('风暴', '飓风', 8.5, 'manual'),
('沙漠', '绿洲', 7.3, 'manual'),
('糖', '盐', 6.1, 'manual'),
('耳朵', '眼睛', 7.2, 'manual'),
('鼻子', '嘴巴', 7.0, 'manual'),
('铅笔', '画笔', 6.5, 'manual'),
('皮带', '领带', 6.2, 'manual'),
('国王', '皇帝', 8.3, 'manual'),
('皇后', '公主', 7.5, 'manual'),
('黄金', '白银', 7.4, 'manual'),
('婴儿', '儿童', 7.1, 'manual'),
('云', '雨', 6.3, 'manual'),
('狐狸', '狼', 7.2, 'manual'),
('田野', '森林', 8.2, 'manual'),
('刀', '剑', 8.4, 'manual'),
('笔记本电脑', '台式机', 8.1, 'manual'),
('圆形', '方形', 6.2, 'manual'),
('三角形', '矩形', 6.0, 'manual'),
('火箭', '卫星', 8.6, 'manual'),
('植物', '花卉', 6.5, 'manual'),
('王国', '帝国', 8.5, 'manual'),
('岛屿', '大陆', 7.2, 'manual'),
('表兄弟', '兄弟', 6.5, 'manual'),
('镜子', '窗户', 7.0, 'manual'),
('绳子', '线', 6.4, 'manual'),
('诗人', '作家', 7.2, 'manual');